Sprint 6/step 1
AlexandrBlaze/react-burger pull request #8
Opened 2023-11-21 21:51 UTC by AlexandrBlaze

2023-11-22 03:39 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец!**

- Все юнит-тесты (45 шт) проходят успешно

### **Есть несколько замечаний, которые нужно исправить:**

- Кажется, вы забыли запушить `cypress` тесты.

  - ~~Сразу напишу, лучше вынести базовый адрес сервера в конфиг cypress.
    <https://docs.cypress.io/guides/references/best-practices#Setting-a-Global-baseUrl>~~
    
    Увидел что у вас есть уже это)) 👍

- Добавьте в `readme` ссылку на проект.

### **Сделает код лучше:**

- Сразу напишу: Лучше разделить cypress тесты на разные файлы, так вы ограничите области которые тестируете. Так сразу будет понятно, какой файл, за какой функционал отвечает;

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>;

2023-11-22 17:00 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Практически все замечания были исправлены!

### **Вы молодец!**

### **Но есть несколько замечаний, которые нужно исправить:**

- По чек-листу требуется написать Cypress-тесты:

  - открытие модального окна с описанием ингредиента,
  - отображение в модальном окне данных ингредиента,
  - закрытие модальных окон при клике на кнопку закрытия.

  Желательно сделать 3 отдельный кейса. Т.е. там будет 3 `it(...)`

### **Сделает код лучше:**

- Хорошей практикой является использовать такие названия для тест-кейсов:

  - Для `describe`: `test (что мы будем тестировать)`, пример: `test sorting algorithms`;
  - Для `it`: `should (каким должен быть результат/при каких параметрах)`, пример: `should correct sort empty array`, `should correct sort array with only one element`;

2023-11-23 11:51 UTC, ArslanMustafin approved these changes
## Code Review

Здравствуйте!

Отличная работа.🔥

### **Вы молодец! Работа принята.**

Несколько советов для дальнейшего развития:

- Сверстайте несколько небольших проектов для себя, для закрепления знаний, и чтобы можно добавить их в портфолио.

- Ходите на собеседования: опыт прохождения собеседований не менее важен знаний теории, и Вы поймете, какие знания требуются на рынке, и где Вы проседаете.

- Читайте habr и слушаете подкаксты: они очень хорошо расширяют кругозор и позволяют узнать, что происходит в отрасли.

2023-11-23 11:51 UTC, ArslanMustafin commented on cypress/e2e/spec.cy.ts
> +  });
**Можно лучше:**

не совсем понял почему вы не смогли сделать просто 3 разных кейса.

Можно сделать например вот так:
```js
/* тестируем открытие модального окна ингредиента, закрытие по кнопке и закрытие
   по клику на оверлей (по оверлею в "Можно лучше") */
describe("ingredient modal works correctly", function () {
  beforeEach(function () {
    cy.intercept("GET", "api/ingredients", { fixture: "ingredients.json" });
    cy.viewport(1300, 800);
    cy.visit("http://localhost:3000");
  });

  it("should work open modal", function () {
    cy.contains("Детали ингредиента").should("not.exist");
    cy.contains("Ингредиент 1").click();
    cy.contains("Детали ингредиента").should("exist");
    cy.get("#modals").contains("Ингредиент 1").should("exist");
  });

  it("should work close modal on button click", function () {
    cy.contains("Ингредиент 1").click();
    cy.contains("Детали ингредиента").should("exist");
    cy.get('#modals button[aria-label="закрыть"]').click();
    cy.contains("Детали ингредиента").should("not.exist");
  });

  it("should work close modal on overlay click", function () {
    cy.contains("Ингредиент 1").click();
    cy.contains("Детали ингредиента").should("exist");
    cy.get("[data-cy=modal-overlay]").click("left", { force: true });
    cy.contains("Детали ингредиента").should("not.exist");
  });
});
```

2023-12-04 09:28 UTC, merged

2023-12-04 09:30 UTC, AlexandrBlaze commented on cypress/e2e/spec.cy.ts
> +  });
Возможно из за отсутствия дополнительных проверок не получилось, теперь знаю как )